baseurl = "https://simt.io/"
title = "Simon Tesar"
languageCode = "en-us"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

defaultContentLanguage = "en"
archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  description = "Personal homepage"
  homeSubtitle = "That infrastructure guy"
  logo = "fa-cubes"
  copyright = "Simon Tesar"

  customCSS = []
  customJS  = []
  footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
  footerRight = "Made in Austria"

  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/simt2"

[[params.social]]
  medium = "stackoverflow"
  icon = "stack-overflow"
  link = "https://stackoverflow.com/users/1336399/simon-tesar"

[languages]
[languages.en]
languageName = "English"
weight = 1
keywords = ""
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
readOtherPosts = "Read other posts"

[languages.en.params.logo]
  logoText = "hello friend ng"
  logoHomeLink = "/"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"